server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oa?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password: redis

#  freemarker:
#    suffix: .ftl
#    expose-request-attributes: true
#    expose-session-attributes: true
#    request-context-attribute: request

mybatis-plus:
  type-enums-package: tech.hongjian.oa.entity.enums
  type-aliases-package: tech.hongjian.oa.entity
  global-config:
    db-config:
      id-type: auto

# log配置
logging:
  level:
    tech.hongjian.oa.mapper: debug

# flowable 配置
flowable:
  # 关闭异步，不关闭历史数据的插入就是异步的，会在同一个事物里面，无法回滚
  # 开发可开启会提高些效率，上线需要关闭
  async-executor-activate: false
#  database-schema-update: true
sys:
  token:
    expire: 30 # token有效时长，单位分钟
    refresh-interval: 5 # token刷新周期，单位分钟
