server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oa?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password: redis

#  freemarker:
#    suffix: .ftl
#    expose-request-attributes: true
#    expose-session-attributes: true
#    request-context-attribute: request

mybatis-plus:
  type-enums-package: tech.hongjian.oa.entity.enums
  type-aliases-package: tech.hongjian.oa.entity
  global-config:
    db-config:
      id-type: auto

sys:
  token:
    expire: 30 # token有效时长，单位分钟
    refresh-interval: 5 # token刷新周期，单位分钟
logging:
  level:
    tech.hongjian.oa.mapper: debug
