spring:
  datasource:
    url: jdbc:mysql://pi.home:3306/oa?useUnicode=true&useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
